id: I48EECC69
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:27:46.921260
last_modified: 2023-02-10 00:27:46.921410
source_metadata:
  title: 'Candrakīrti: Madhyamakāvatāra'
  language: bo
bases:
  ACF0:
    base_file: ACF0.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
